version: '3'
services:

  react-api:
    image: aws-react-api
    container_name: aws-react-api
    build: ./api
    restart: always
    ports:
      - '8085:8085'
    depends_on:
      - mongodb

  react-ui:
    image: aws-react-ui
    container_name: aws-react-ui
    build: ./ui
    restart: on-failure
    depends_on:
      - mongodb
      - react-api
    environment:
      - REACT_APP_APPLICATION_VERSION = v1.0
    env_file:
      - application.env
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017-27019:27017-27019'